#:kivy 2.3.0 
#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import NoTransition kivy.uix.screenmanager.NoTransition

Manager:

<Manager>:
    HomePage:
    Profile:
    Help:
    Setting:
    Stats:
    Basic_Games:
    Basic_Math_Game_1:
    Lessons:

        

#page which starts just after opening app, second time onwards
<HomePage>:
    name: "home"
    FloatLayout:
        # background 
        canvas.before:
            Rectangle: 
                source: r"Project_Nabha\Images\background.png"               
                pos: self.pos
                size: self.size
        # profile button dispalay
        BoxLayout:
            orientation: "horizontal"
            size_hint: 0.25, 0.07
            pos_hint: {"x": 0, "top": 1}
            Button:
                canvas.before:
                    Color:
                        rgba: (0, 0, 0, 1)   
                    Line:
                        width: 2
                        rectangle: (self.x, self.y, self.width, self.height)
                background_normal: r"Project_Nabha\Images\profile.png"
                border: [0,0,0,0]
                #text: "profile"
                size_hint_y: 1
                size_hint_x: None
                width: self.height
                on_release:
                    app.root.current="profile"
                    app.root.transition.direction="down"
            # user's name
            BoxLayout:
                orientation: "vertical"
                canvas.before:
                    Color:
                        rgba: (0, 0, 0, 1)   
                    Line:
                        width: 2
                        rectangle: (self.x, self.y, self.width, self.height)
                Button:
                    background_normal:""
                    background_color: (1,1,1,1)
                    text: "Name: user_1"
                    color: (0,0,0,1)
                    font_size: min(self.width, self.height) * 0.4
                    on_release:
                        app.root.current="profile"
                        app.root.transition.direction="down"
                # user's level
                Button:
                    background_normal:""
                    background_color: (1,1,1,1)
                    text: "Level: 1"
                    color: (0,0,0,1)
                    font_size: min(self.width, self.height) * 0.4
                    on_release:
                        app.root.current="profile"
                        app.root.transition.direction="down"
            
        # for coins
        Label:
            canvas.before:
                Color:
                    rgba: (1,1,1,1)
                Rectangle:
                    pos: self.pos
                    size: self.size
                Color:
                    rgba: (0, 0, 0, 1)
                Line:
                    width: 2
                    rectangle: (self.x, self.y, self.width, self.height)
            text: "coins: 0"
            color: (0,0,0,1)
            size_hint: 0.45, 0.07
            pos_hint: {"center_x": 0.5, "top": 1}
        # help
        Button:
            background_normal: r"Project_Nabha\Images\help.png"
            #text: "help"
            size_hint: 0.1, 0.07
            pos_hint: {"right": 0.87, "top": 1}
            on_release:
                app.root.current="help"
                app.root.transition.direction="down"
        # settings
        Button:
            canvas.before:
                Color:
                    rgba: (0, 0, 0, 1)   
                Line:
                    width: 2
                    rectangle: (self.x, self.y, self.width, self.height)
            background_normal: r"Project_Nabha\Images\settings.png"
            border: [0,0,0,0]
            #text: "setting"
            size_hint: 0.1, 0.07
            pos_hint: {"right": 1, "top": 1}
            on_release:
                app.root.current="setting"
                app.root.transition.direction="down"

        # achievements: also have badges
        Button:
            background_normal: r"Project_Nabha\Images\achievements.png"
            border: [0,0,0,0]
            #text: "achievements"
            size_hint: 0.15, 0.07
            pos_hint: {"x": 0.025, "top": 0.55}
        # gallery: collection of ttrophies and badges
        Button:
            background_normal: r"Project_Nabha\Images\gallery.png"
            border: [0,0,0,0]
            #text: "gallery"
            size_hint: 0.15, 0.07
            pos_hint: {"x": 0.025, "top": 0.45}

        # stats: studen't progress, ranking board
        Button:
            background_normal: r"Project_Nabha\Images\stats.png"
            border: [0,0,0,0]
            #text: "stats"
            size_hint: 0.15, 0.07
            pos_hint: {"right": 0.975, "top": 0.55}
            on_release:
                app.root.current="stats"
                app.root.transition.direction = "left"
        # store: need to think about it.
        Button:
            background_normal: r"Project_Nabha\Images\store.png"
            border: [0,0,0,0]
            #text: "store"
            size_hint: 0.15, 0.07
            pos_hint: {"right": 0.975, "top": 0.45}
        # rewards(make it prompt): daily task, maybe weekly task later
        Button:
            background_normal: r"Project_Nabha\Images\tasks.png"
            border: [0,0,0,0]
            #text: "rewards"
            size_hint: 0.15, 0.07
            pos_hint: {"right": 0.875, "top": 0.35}

        # basic games: pre installed games
        Button:
            background_normal: r"Project_Nabha\Images\basic_games.png"
            border: [0,0,0,0]
            #text: "BASIC GAMES"
            size_hint: 0.25, 0.125
            pos_hint: {"x": 0, "y": 0}
            on_release:
                app.root.current="Basic_Games"
                app.root.transition.direction="up"
        # lessons: class material 6-10
        Button:
            background_normal: r"Project_Nabha\Images\lessons.png"
            border: [0,0,0,0]
            #text: "LESSONS"
            size_hint: 0.4, 0.175
            pos_hint: {"center_x": 0.5, "y": 0}
            on_release:
                app.root.current="lessons"
                app.root.transition.direction = "up"
        # other games: extra learning games
        Button:
            background_normal: r"Project_Nabha\Images\other_games.png"
            border: [0,0,0,0]
            #text: "OTHER GAMES"
            size_hint: 0.25, 0.125
            pos_hint: {"right": 1, "y": 0}

        # show off panel, does not have any class in py file
        FloatLayout:
            # platform
            Label:
                pos_hint: {"center_x": 0.5, "center_y": 0.3}
                size_hint: 0.4, 0.1
                canvas.before:
                    Rectangle:
                        source: r"Project_Nabha\Images\platform.png"
                        pos: self.pos
                        size: self.size
            # middle 
            Label:
                pos_hint: {"center_x": 0.5, "center_y": 0.47}
                size_hint: 0.15, 0.27
                canvas.after:
                    Rectangle:
                        source: r"Project_Nabha\Images\medal_1.png"
                        pos: self.pos
                        size: self.size

# changes cannot be made in this directly
<Profile>:
    name: "profile"
    BoxLayout:
        orientation:"vertical"
        BoxLayout:
            orientation:"horizontal"
            size_hint_y:0.3
             #just empty space
            Label:
            # choosen image of user shown here
            Label:
                text: "photo"
            # back button
            FloatLayout:
                Button:
                    text: "back"
                    size_hint: 0.8, 0.25
                    pos_hint: {"right": 0.95, "top": 0.95}
                    on_release:
                        app.root.current="home"
                        app.root.transition.direction="up"
        BoxLayout:
            orientation: "vertical"
            size_hint_y:0.4
            padding: self.width*0.02
            Label:
                text:"level"
            ProgressBar:
                max: 100
                value: 10
                size_hint_x: 0.7
                pos_hint: {"center_x": 0.5}
            Label:
                text: "uid: GS000001"
                text_size: self.size
                halign: "left"
            Label:
                text: "Name: user1"
                text_size: self.size
                halign: "left"
            Label:
                text: "Title: Beginner"
                text_size: self.size
                halign: "left"
            Label:
                text: "coins : 0"
                text_size: self.size
                halign: "left"
            Label:
                text: "-Collection-"
        # shows the badges or trophies
        BoxLayout:
            orientation:"horizontal"
            size_hint_y: 0.3
            Label:
                text: "image 1"
            Label:
                text: "image 2"
            Label:
                text: "image 3"
            Label:
                text: "image 4"
            Label:
                text: "image 5"

# help screen containing description of things
<Help>:
    name: "help"
    BoxLayout:
        orientation: "vertical"
        AnchorLayout:
            anchor_x: "right"
            anchor_y: "top"
            size_hint_y: 0.08
            Button:
                text: "Home"
                size_hint_x: 0.15
                on_release:
                    app.root.current= "home"
                    app.root.transition.direction= "up"
        ScrollView:
            do_scroll_x: False
            Label:
                padding: self.width*0.03
                text: 
                    """hello this is help menu \n
                    this is first line \n
                    you can fing about everyting here\n
                    not only in english\n
                    but in punjabui too\n
                    along with some picture as a depiction\n
                    etc\n
                    etc\n
                    now i don't have words left to say\n
                    i'm thinking of storing this text from database \n
                    but i guess it will be beter if it comes\n
                    built in\n
                    though i don't know how to set pctures yet\n
                    i mean i can set background \n
                    and button pics\n
                    but not inside this \n
                    """
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

# setting
<Setting>:
    name: "setting"
    FloatLayout:
        Button:
            text: "back"
            size_hint: 0.2, 0.08
            pos_hint: {"right": 0.9, "top": 0.9}
            on_release:
                app.root.current="home"
                app.root.transition.direction="up"
        # button to close the app, need to add save button
        Button:
            text: "exit"
            size_hint: 0.2, 0.08
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            on_release: app.stop()

# contains the data of user(for parents or teacher)
# also contain leaderboard for when there is internet
<Stats>:
    name: "stats"
    BoxLayout:
        orientation: "vertical"
        # top bar having back button
        AnchorLayout:
            anchor_x: "left"
            anchor_y: "top"
            size_hint_y: 0.1
            BoxLayout:
                orientation: "horizontal"
                Button:
                    text: "back"
                    size_hint_x: 0.2
                    on_release:
                        app.root.current="home"
                        app.root.transition.direction = "right"
                # changes the title here
                Label:
                    text: "title"
                    size_hint_x: 0.4
                Label:
                    text: "coins: 0"
                    size_hint_x: 0.4
        # data will be on these pages     
        PageLayout:
            id: data
            size_hint: 0.85, 1
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            # for personal progress and data
            Label:
                text: "progress here"
            # for online ranking
            Label:
                text: "leaderboard here"
        # bottom bar having switch screen buttons
        AnchorLayout:
            anchor_y: "bottom"
            size_hint_y: 0.15
            BoxLayout:
                orientation: "horizontal"
                padding: self.width*0.02, self.height*0.02
                Button:
                    text: "Progress"
                    on_release: data.page=0
                Button:
                    text: "Ranking"
                    on_release: data.page=1



# basic games : contain preinstalled games
<Basic_Games>:
    name: "Basic_Games"
    BoxLayout:
        orientation: "vertical"
        # header containing back button etc
        AnchorLayout:
            anchor_y: "top"
            size_hint_y: 0.1
            BoxLayout:
                orientation: "horizontal"
                Button:
                    text: "back"
                    size_hint_x: 0.2
                    on_release:
                        app.root.current="home"
                        app.root.transition.direction = "down"
                Label:
                    text: "Basic Games"
                    size_hint_x: 0.3
                Label:
                    text: "coins: 0"
                    size_hint_x: 0.3
                Button:
                    text: "home"
                    size_hint_x: 0.2
                    on_release:
                        app.root.current="home"
                        app.root.transition=NoTransition()
        ScrollView:
            do_scroll_x: False
            #padding: [self.width*0.05]
            GridLayout:
                cols: 1
                row_force_default: True #mandatory if default value is used
                col_force_default: True
                col_default_width: self.width*0.95
                row_default_height: self.col_default_width/5
                size_hint_y: None
                height: self.minimum_height
                padding: [self.width*0.02,0,0,0]
                #game 1: knight vs dragon option
                BoxLayout:
                    orientation: "horizontal"
                    # game's thumbnail
                    Button:
                        text: "game icon"
                        size_hint_x:None
                        width: self.height 
                    # play button and name of game
                    BoxLayout:
                        orientation: "vertical"
                        Label:
                            text: "Knight vs Dradon"
                        BoxLayout:
                            orientation: "horizontal"
                            padding: [self.width*0.01,0,self.width*0.01,0]
                            spacing: self.width*0.1
                            Button:
                                text: "play"
                                on_release:
                                    app.root.current="Basic_Math_Game_1"
                                    app.root.transition.direction="up"
                            Button:
                                text: "help"
                        # difficulty of game
                        BoxLayout:
                            orientation: "horizontal"
                            padding: [self.width*0.01,0,self.width*0.01,0]
                            spacing: self.width*0.01
                            ToggleButton:
                                id: easy
                                text: "Easy"
                                group: "level"
                                state: "down" # default 
                                on_release:
                                    root.difficult(self.text,"Basic_Math_Game_1") #chooses diffuculty for games
                            ToggleButton:
                                id: medium
                                text: "Medium"
                                group: "level"
                                on_release:
                                    root.difficult(self.text,"Basic_Math_Game_1")
                            ToggleButton:
                                id: hard
                                text: "Hard"
                                group: "level"
                                on_release:
                                    root.difficult(self.text,"Basic_Math_Game_1")
                # game 2 option
                Button:
                    text: "button 2"
                    disabled: True

# game 1: knight vs dragon; Basic_Math_Game_1

<Basic_Math_Game_1>:
    name: "Basic_Math_Game_1"
    BoxLayout:
        orientation: "vertical"
        # top bar to show points and back button
        BoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.07
            #difficulty
            Label:
                canvas.before:
                    Color:
                        rgba: (1,1,1,1)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                size_hint_x: 0.3
                text: "Mode: "+ root.difficulty
                color: (0,0,0,1)
            #points
            Label:
                canvas.before:
                    Color:
                        rgba: (1,1,1,1)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                size_hint_x: 0.5
                text: "Points: "+ str(root.points)
                color: (0,0,0,1)
            Button:
                size_hint_x: 0.2
                text: "Exit"
                background_normal: ""
                background_color: (1,0,0,1)
                on_release:
                    app.root.current="Basic_Games"
                    app.root.transition.direction="down"

        # animation space ( knight & dragon)
        BoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.43
            canvas.before:
                Rectangle:
                    source: r"Project_Nabha\Images\kvd_background.png"
                    pos: self.pos
                    size: self.size
            padding: [self.width * 0.25, self.height * 0.03, self.width * 0.05, self.height*0.05]
            # hero
            BoxLayout:
                orientation: "vertical"
                size_hint_x: 0.25
                # top space
                Label:
                    size_hint_y: 0.62
                #health bar 
                ProgressBar:
                    max: 60
                    value: 55
                    size_hint: 0.5, 0.08
                    pos_hint: {"center_x": 0.5}
                # hero image
                Label:
                    size_hint_y: 0.3
                    canvas.after:
                        Rectangle:
                            source: r"Project_Nabha\Images\knight.png"
                            pos: self.pos
                            size: self.size
            # empty space
            Label:
                size_hint_x: 0.35
            # evil dragon
            BoxLayout:
                orientation: "vertical"
                size_hint_x: 0.4
                # top space
                Label:
                    size_hint_y: 0.6
                # health bar
                ProgressBar:
                    max: 20
                    value: 19
                    size_hint: 0.5, 0.08
                    pos_hint: {"center_x": 0.5}
                # dragon image
                Label:
                    canvas.after:
                        Rectangle:
                            source: r"Project_Nabha\Images\dragon.png"
                            pos: self.pos
                            size: self.size
                    

        # question and answer dispaly bar
        BoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.1
            # wihite background
            canvas.before:
                Color:
                    rgba: (1,1,1,1)
                Rectangle:
                    size: self.size
                    pos: self.pos
            # question display
            Label:
                size_hint_x: 0.50
                text: root.ques_text
                font_size: min(self.width, self.height)*0.5
                # black text
                color: (0,0,0,1)
            Label:
                size_hint_x: 0.05
                text:"="
                font_size: min(self.width, self.height)*0.5
                color: (0,0,0,1)
            # answer display
            Label:
                size_hint_x: 0.30
                text: root.ans_text
                font_size: min(self.width, self.height)*0.5
                color: (0,0,0,1)
            # delete button
            Button:
                background_normal: r"Project_Nabha\Images\blue_button.png"
                border: [0,0,0,0]
                size_hint_x: 0.15
                text: "Delete"
                font_size: min(self.width, self.height)*0.35
                on_press:
                    root.delete()
        # keypad
        BoxLayout:
            orientation: "horizontal"
            size_hint_y: 0.5
            padding: self.width*0.01
            GridLayout:
                cols: 3
                size_hint_x: 0.7
                padding: self.width*0.01
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "1"
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("1")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "2"
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("2")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "3"    
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("3")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "4"
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("4")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "5"
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("5")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "6" 
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("6")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "7"
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("7")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "8"
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("8")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "9" 
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("9")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "+ , -"
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.uni_opera()
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "0"
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad("0")
                Button:
                    background_normal: r"Project_Nabha\Images\blue_button.png"
                    border: [0,0,0,0]
                    text: "." 
                    font_size: min(self.width, self.height)*0.7
                    on_press:
                        root.keypad(".")
            Button:
                background_normal: r"Project_Nabha\Images\blue_button.png"
                border: [0,0,0,0]
                size_hint_x: 0.3
                text: "Enter"
                font_size: min(self.width, self.height)*0.2
                on_press:
                    root.enter()



# contains games related to syllabus from class 6-12
<Lessons>:
    name: "lessons"
    BoxLayout:
        orientation:"vertical"
        # header containing back button etc
        AnchorLayout:
            #anchor_x: "left"
            anchor_y: "top"
            size_hint_y: 0.1
            BoxLayout:
                orientation: "horizontal"
                Button:
                    text: "back"
                    size_hint_x: 0.2
                    on_release:
                        app.root.current="home"
                        app.root.transition.direction = "down"
                Label:
                    text: "Lessons"
                    size_hint_x: 0.3
                Label:
                    text: "coins: 0"
                    size_hint_x: 0.3
                Button:
                    text: "home"
                    size_hint_x: 0.2
                    on_release:
                        app.root.current="home"
                        app.root.transition=NoTransition()
        # scrollable boxes, each one for every class
        ScrollView:
            do_scroll_x: False
            GridLayout:
                cols: 3
                row_force_default: True #mandatory if default value is used
                col_force_default: True
                col_default_width: self.width/3.15
                row_default_height: self.col_default_width #for square boxes
                size_hint_y: None
                height: self.minimum_height #for auto adjust of scroll view
                padding: [self.width * 0.018, self.height * 0.018, self.width * 0.018, self.height * 0.018]

                Button:
                    text:"class 6"
                Button:
                    text:"class 7"
                Button:
                    text:"class 8"
                Button:
                    text:"class 9"
                Button:
                    text:"class 10"
                Button:
                    text:"class 11"
                Button:
                    text:"class 12"